"""Tests for the exporter graph node."""

from __future__ import annotations

from pathlib import Path
from typing import Any
from unittest.mock import MagicMock, patch

from ainews.agents.state import GraphState, NodeError

# ── Fixtures ──────────────────────────────────────────────

VALID_REPORT_MD = """\
# AI News & Trends Report
*Generated: 2026-05-08 10:00 UTC*
*Topics: AI | Window: 7 days*

## Executive Summary

Executive summary text.

## Top Stories

### 1. Test Story

- Bullet one

## Methodology

This report was generated by the AI News & Trends pipeline.
"""

SAMPLE_SUMMARIES: list[dict[str, Any]] = [
    {
        "cluster_id": "c1",
        "headline": "Test Story",
        "bullets": ["Bullet one"],
        "why_it_matters": "Important",
        "sources": ["https://example.com"],
    },
]

SAMPLE_TRENDS: list[dict[str, Any]] = [
    {
        "name": "Test Trend",
        "description": "A test trend.",
        "evidence_cluster_ids": ["c1"],
    },
]


def _make_state(
    *,
    tmp_path: Path,
    report_md: str = VALID_REPORT_MD,
    summaries: list[dict[str, Any]] | None = None,
    trends: list[dict[str, Any]] | None = None,
    errors: list[NodeError] | None = None,
) -> GraphState:
    """Build a minimal GraphState for exporter tests."""
    return GraphState(
        run_id="test-run-001",
        params={"topics": ["AI"], "timeframe_days": 7, "sites": []},
        queries=[],
        raw_results=[],
        fetched_articles=[],
        filtered_articles=[],
        clusters=[],
        summaries=summaries if summaries is not None else SAMPLE_SUMMARIES,
        trends=trends if trends is not None else SAMPLE_TRENDS,
        report_md=report_md,
        xlsx_path="",
        errors=errors or [],
        metrics={},
        loop_count=0,
    )


# ── Tests ──────────────────────────────────────────────────


class TestExporterNode:
    """Tests for exporter_node function."""

    @patch("ainews.agents.nodes.exporter.get_db_session")
    @patch("ainews.agents.nodes.exporter._get_reports_dir")
    def test_calls_both_exporters(
        self, mock_reports_dir: MagicMock, mock_db: MagicMock, tmp_path: Path
    ) -> None:
        """Exporter node produces both .md and .xlsx files."""
        mock_reports_dir.return_value = tmp_path
        mock_session = MagicMock()
        mock_db.return_value.__enter__ = MagicMock(return_value=mock_session)
        mock_db.return_value.__exit__ = MagicMock(return_value=False)

        from ainews.agents.nodes.exporter import exporter_node

        state = _make_state(tmp_path=tmp_path)
        exporter_node.__wrapped__(state)  # type: ignore[attr-defined]

        # Check both files created
        md_path = tmp_path / "test-run-001" / "report.md"
        xlsx_path = tmp_path / "test-run-001" / "report.xlsx"
        assert md_path.exists()
        assert xlsx_path.exists()

    @patch("ainews.agents.nodes.exporter.get_db_session")
    @patch("ainews.agents.nodes.exporter._get_reports_dir")
    def test_returns_xlsx_path_and_metrics(
        self, mock_reports_dir: MagicMock, mock_db: MagicMock, tmp_path: Path
    ) -> None:
        """Exporter returns xlsx_path and metrics in partial state."""
        mock_reports_dir.return_value = tmp_path
        mock_session = MagicMock()
        mock_db.return_value.__enter__ = MagicMock(return_value=mock_session)
        mock_db.return_value.__exit__ = MagicMock(return_value=False)

        from ainews.agents.nodes.exporter import exporter_node

        state = _make_state(tmp_path=tmp_path)
        result = exporter_node.__wrapped__(state)  # type: ignore[attr-defined]

        assert "xlsx_path" in result
        assert "metrics" in result
        assert result["xlsx_path"].endswith("report.xlsx")

    @patch("ainews.agents.nodes.exporter.get_db_session")
    @patch("ainews.agents.nodes.exporter._get_reports_dir")
    def test_creates_db_report_row(
        self, mock_reports_dir: MagicMock, mock_db: MagicMock, tmp_path: Path
    ) -> None:
        """Exporter creates a Report ORM row in the database."""
        mock_reports_dir.return_value = tmp_path
        mock_session = MagicMock()
        mock_db.return_value.__enter__ = MagicMock(return_value=mock_session)
        mock_db.return_value.__exit__ = MagicMock(return_value=False)

        from ainews.agents.nodes.exporter import exporter_node

        state = _make_state(tmp_path=tmp_path)
        exporter_node.__wrapped__(state)  # type: ignore[attr-defined]

        # Verify session.add was called with a Report
        mock_session.add.assert_called_once()
        report_obj = mock_session.add.call_args[0][0]
        assert report_obj.run_id == "test-run-001"
        assert report_obj.full_md_path is not None
        assert report_obj.xlsx_path is not None

    @patch("ainews.agents.nodes.exporter.get_db_session")
    @patch("ainews.agents.nodes.exporter._get_reports_dir")
    def test_resilient_decorator_handles_errors(
        self, mock_reports_dir: MagicMock, mock_db: MagicMock, tmp_path: Path
    ) -> None:
        """@node_resilient catches export failures gracefully."""
        mock_reports_dir.return_value = tmp_path
        mock_db.side_effect = RuntimeError("DB connection failed")

        from ainews.agents.nodes.exporter import exporter_node

        # Pass an invalid report to trigger validation error in md exporter
        state = _make_state(tmp_path=tmp_path, report_md="invalid report")
        result = exporter_node(state)

        # node_resilient catches exceptions and returns errors
        assert "errors" in result
        assert len(result["errors"]) > 0
