"""Writer node — assembles final Markdown report.

Uses Jinja2 template for structure and LLM polish for Executive Summary.
"""

from __future__ import annotations

import time
from datetime import UTC, datetime
from typing import Any

import structlog

from ainews.agents.prompts.loader import load_prompt
from ainews.agents.resilience import node_resilient, track_metrics
from ainews.agents.state import GraphState

logger = structlog.get_logger(__name__)


def _get_llm() -> Any:
    """Lazy-load LLM client from factory."""
    from ainews.core.config import Settings
    from ainews.llm.factory import get_llm, get_llm_config

    settings = Settings()
    config = get_llm_config(settings)
    return get_llm(config)


@node_resilient("writer")
def writer_node(state: GraphState) -> dict[str, Any]:
    """Assemble final Markdown report from summaries and trends.

    Parameters
    ----------
    state
        Current graph state with ``summaries``, ``trends``, and ``errors``.

    Returns
    -------
    dict
        Partial state with ``report_md``.
    """
    start = time.time()
    summaries = state.get("summaries", [])
    trends = state.get("trends", [])
    errors = state.get("errors", [])
    params = state["params"]

    # Build report sections
    sections: list[str] = []
    now = datetime.now(tz=UTC).strftime("%Y-%m-%d %H:%M UTC")

    # Header
    sections.append("# AI News & Trends Report")
    sections.append(f"*Generated: {now}*")
    sections.append(
        f"*Topics: {', '.join(params['topics'])} | "
        f"Window: {params['timeframe_days']} days*"
    )
    sections.append("")

    # Degradation notice if errors present
    if errors:
        sections.append(
            "> ⚠️ **Note:** This report was generated with partial data. "
            f"Some pipeline stages encountered errors ({len(errors)} total). "
            "Results may be incomplete."
        )
        sections.append("")

    # Executive Summary (LLM polished)
    executive_summary = _generate_executive_summary(summaries, trends)
    sections.append("## Executive Summary")
    sections.append("")
    sections.append(executive_summary)
    sections.append("")

    # Top Stories
    sections.append("## Top Stories")
    sections.append("")
    for i, summary in enumerate(summaries, 1):
        sections.append(f"### {i}. {summary['headline']}")
        sections.append("")
        for bullet in summary.get("bullets", []):
            sections.append(f"- {bullet}")
        sections.append("")
        if summary.get("why_it_matters"):
            sections.append(f"**Why It Matters:** {summary['why_it_matters']}")
            sections.append("")
        if summary.get("sources"):
            sections.append("**Sources:**")
            for src in summary["sources"]:
                sections.append(f"- {src}")
            sections.append("")

    # Trends
    if trends:
        sections.append("## Key Trends")
        sections.append("")
        for i, trend in enumerate(trends, 1):
            sections.append(f"### {i}. {trend['name']}")
            sections.append("")
            sections.append(trend["description"])
            sections.append("")

    # Methodology
    sections.append("## Methodology")
    sections.append("")
    sections.append(
        "This report was generated by the AI News & Trends pipeline. "
        "Articles were gathered via Tavily search, filtered by LLM-based "
        "relevance scoring, deduplicated, and synthesized into summaries. "
        "Trends were identified through cross-cluster analysis."
    )
    sections.append("")

    report_md = "\n".join(sections)

    logger.info(
        "writer_complete",
        report_length=len(report_md),
        summary_count=len(summaries),
        trend_count=len(trends),
    )

    return {
        "report_md": report_md,
        "metrics": track_metrics("writer", state, start_time=start),
    }


def _generate_executive_summary(
    summaries: list[Any],
    trends: list[Any],
) -> str:
    """Generate polished executive summary via LLM.

    Falls back to a simple concatenation if LLM fails.
    """
    if not summaries:
        return "No stories to summarize."

    summaries_text = "\n".join(
        f"- {s.get('headline', 'Untitled')}: " + "; ".join(s.get("bullets", [])[:2])
        for s in summaries
    )
    trends_text = (
        "\n".join(
            f"- {t.get('name', 'Unnamed')}: {t.get('description', '')}" for t in trends
        )
        if trends
        else "No specific trends identified."
    )

    try:
        prompt = load_prompt(
            "writer_executive",
            summaries_text=summaries_text,
            trends_text=trends_text,
        )
        llm = _get_llm()
        response = llm.invoke(prompt)
        executive: str = response.content
        return executive.strip()
    except Exception as exc:
        logger.warning("writer_executive_llm_error", error=str(exc))
        # Fallback
        return (
            "This week's key developments include: "
            + "; ".join(s.get("headline", "") for s in summaries[:5])
            + "."
        )
