"""Tests for the Markdown exporter and Pydantic validation schemas."""

from __future__ import annotations

from pathlib import Path

import pytest
from pydantic import ValidationError

from ainews.schemas.report_output import ReportOutput

# ── Sample data ──────────────────────────────────────────

VALID_REPORT_MD = """\
# AI News & Trends Report
*Generated: 2026-05-08 10:00 UTC*
*Topics: AI | Window: 7 days*

## Executive Summary

This is the executive summary.

## Top Stories

### 1. Test Story

- Bullet one

## Methodology

This report was generated by the AI News & Trends pipeline.
"""


# ── Markdown exporter tests ──────────────────────────────


class TestExportMarkdown:
    """Tests for export_markdown function."""

    def test_creates_file(self, tmp_path: Path) -> None:
        """Markdown file is created at expected path."""
        from ainews.exporters.markdown import export_markdown

        result = export_markdown(VALID_REPORT_MD, "run-001", tmp_path)
        assert result.exists()
        assert result.name == "report.md"

    def test_correct_content(self, tmp_path: Path) -> None:
        """Written file contains the exact report_md content."""
        from ainews.exporters.markdown import export_markdown

        result = export_markdown(VALID_REPORT_MD, "run-001", tmp_path)
        content = result.read_text(encoding="utf-8")
        assert content == VALID_REPORT_MD

    def test_directory_auto_creation(self, tmp_path: Path) -> None:
        """Creates {reports_dir}/{run_id}/ directory if not exists."""
        from ainews.exporters.markdown import export_markdown

        result = export_markdown(VALID_REPORT_MD, "run-001", tmp_path)
        assert result.parent.name == "run-001"
        assert result.parent.is_dir()

    def test_returned_path_is_absolute(self, tmp_path: Path) -> None:
        """Returned path is absolute."""
        from ainews.exporters.markdown import export_markdown

        result = export_markdown(VALID_REPORT_MD, "run-001", tmp_path)
        assert result.is_absolute()

    def test_nested_run_id(self, tmp_path: Path) -> None:
        """Handles run_id with special characters."""
        from ainews.exporters.markdown import export_markdown

        result = export_markdown(VALID_REPORT_MD, "run_2026-05-08_001", tmp_path)
        assert result.exists()
        assert "run_2026-05-08_001" in str(result)


# ── Pydantic schema tests ────────────────────────────────


class TestReportOutputValidation:
    """Tests for ReportOutput validation schema."""

    def test_valid_output(self, tmp_path: Path) -> None:
        """Valid report passes validation."""
        path = tmp_path / "report.md"
        path.write_text(VALID_REPORT_MD)
        result = ReportOutput(report_md=VALID_REPORT_MD, file_path=path)
        assert result.report_md == VALID_REPORT_MD

    def test_empty_report_md_rejected(self, tmp_path: Path) -> None:
        """Empty report_md is rejected."""
        path = tmp_path / "report.md"
        path.write_text("")
        with pytest.raises(ValidationError, match="report_md must not be empty"):
            ReportOutput(report_md="", file_path=path)

    def test_whitespace_only_rejected(self, tmp_path: Path) -> None:
        """Whitespace-only report_md is rejected."""
        path = tmp_path / "report.md"
        path.write_text("   \n\n  ")
        with pytest.raises(ValidationError, match="report_md must not be empty"):
            ReportOutput(report_md="   \n\n  ", file_path=path)

    def test_missing_sections_rejected(self, tmp_path: Path) -> None:
        """Report without required sections is rejected."""
        path = tmp_path / "report.md"
        incomplete = "# Some Report\n\nContent without required sections."
        path.write_text(incomplete)
        with pytest.raises(ValidationError, match="missing required section"):
            ReportOutput(report_md=incomplete, file_path=path)

    def test_missing_methodology_rejected(self, tmp_path: Path) -> None:
        """Report without Methodology section is rejected."""
        path = tmp_path / "report.md"
        no_methodology = "# AI News & Trends Report\n## Executive Summary\nContent.\n"
        path.write_text(no_methodology)
        with pytest.raises(ValidationError, match="Methodology"):
            ReportOutput(report_md=no_methodology, file_path=path)
