"""Add use_smart_planner to schedules

Revision ID: 3a61b1c8c1b0
Revises: dc24a2937581
Create Date: 2026-05-08 18:14:10.251311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a61b1c8c1b0'
down_revision: Union[str, Sequence[str], None] = 'dc24a2937581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_smart_planner', sa.Integer(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_column('use_smart_planner')
    # ### end Alembic commands ###
