"""baseline_all_tables

Revision ID: dc09fc4f2f6d
Revises: 
Create Date: 2026-05-07 23:22:12.784002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc09fc4f2f6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cron_expr', sa.String(), nullable=False),
    sa.Column('timeframe_days', sa.Integer(), nullable=False),
    sa.Column('site_filter', sa.JSON(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('model_override', sa.String(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index('ix_schedules_enabled', ['enabled'], unique=False)

    op.create_table('settings_kv',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('crawl_depth', sa.Integer(), nullable=False),
    sa.Column('selectors', sa.JSON(), nullable=True),
    sa.Column('js_render', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index('ix_sites_category', ['category'], unique=False)
        batch_op.create_index('ix_sites_enabled', ['enabled'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_pw', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('finished_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('input_params', sa.JSON(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index('ix_runs_schedule_id', ['schedule_id'], unique=False)
        batch_op.create_index('ix_runs_status', ['status'], unique=False)

    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content_md', sa.String(), nullable=True),
    sa.Column('relevance', sa.Float(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('shingles', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'url', name='uq_articles_run_id_url')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index('ix_articles_hash', ['hash'], unique=False)
        batch_op.create_index('ix_articles_run_id', ['run_id'], unique=False)
        batch_op.create_index('ix_articles_status', ['status'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('summary_md', sa.String(), nullable=True),
    sa.Column('html_path', sa.String(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('trends', sa.JSON(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('ix_reports_run_id', ['run_id'], unique=False)

    op.create_table('run_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('node', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('ts', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_logs', schema=None) as batch_op:
        batch_op.create_index('ix_run_logs_level', ['level'], unique=False)
        batch_op.create_index('ix_run_logs_run_id', ['run_id'], unique=False)

    # ### end Alembic commands ###

    # FTS5 virtual table for full-text search on reports
    op.execute(
        "CREATE VIRTUAL TABLE reports_fts"
        " USING fts5(title, summary_md, content=reports, content_rowid=id)"
    )

    # Triggers to keep reports_fts in sync with the reports table
    op.execute(
        "CREATE TRIGGER reports_ai AFTER INSERT ON reports BEGIN"
        "  INSERT INTO reports_fts(rowid, title, summary_md)"
        "  VALUES (new.id, new.title, new.summary_md);"
        " END"
    )
    op.execute(
        "CREATE TRIGGER reports_au AFTER UPDATE ON reports BEGIN"
        "  INSERT INTO reports_fts(reports_fts, rowid, title, summary_md)"
        "  VALUES ('delete', old.id, old.title, old.summary_md);"
        "  INSERT INTO reports_fts(rowid, title, summary_md)"
        "  VALUES (new.id, new.title, new.summary_md);"
        " END"
    )
    op.execute(
        "CREATE TRIGGER reports_ad AFTER DELETE ON reports BEGIN"
        "  INSERT INTO reports_fts(reports_fts, rowid, title, summary_md)"
        "  VALUES ('delete', old.id, old.title, old.summary_md);"
        " END"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_run_logs_run_id')
        batch_op.drop_index('ix_run_logs_level')

    op.drop_table('run_logs')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index('ix_reports_run_id')

    op.drop_table('reports')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index('ix_articles_status')
        batch_op.drop_index('ix_articles_run_id')
        batch_op.drop_index('ix_articles_hash')

    op.drop_table('articles')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('ix_runs_status')
        batch_op.drop_index('ix_runs_schedule_id')

    op.drop_table('runs')
    op.drop_table('users')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index('ix_sites_enabled')
        batch_op.drop_index('ix_sites_category')

    op.drop_table('sites')
    op.drop_table('settings_kv')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index('ix_schedules_enabled')

    op.drop_table('schedules')
    # ### end Alembic commands ###

    # Drop FTS5 triggers and virtual table
    op.execute("DROP TRIGGER IF EXISTS reports_ad")
    op.execute("DROP TRIGGER IF EXISTS reports_au")
    op.execute("DROP TRIGGER IF EXISTS reports_ai")
    op.execute("DROP TABLE IF EXISTS reports_fts")
