"""add missing columns

Revision ID: dc24a2937581
Revises: dc09fc4f2f6d
Create Date: 2026-05-08 16:49:20.206609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc24a2937581'
down_revision: Union[str, Sequence[str], None] = 'dc09fc4f2f6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_md_path', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('xlsx_path', sa.String(), nullable=True))

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('triggered_by', sa.String(), nullable=False, server_default='system'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_column('triggered_by')
        batch_op.drop_column('error')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('xlsx_path')
        batch_op.drop_column('full_md_path')

    # ### end Alembic commands ###
